=== TheHuebschi/xml-webapp/database/challenges.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="challenges">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="challenge"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="challenge">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="title"/>
        <xs:element type="xs:string" name="description"/>
        <xs:element type="xs:string" name="price"/>
        <xs:element ref="registrations"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="companyId" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="registrations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="registration"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="registration">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="date"/>
        <xs:element type="xs:string" name="title"/>
        <xs:element type="xs:string" name="description"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="communityId" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== TheHuebschi/xml-webapp/database/challenges.xml
<?xml version="1.0" ?>
<challenges xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="challenges.xsd">
    <challenge id="1" companyId="1">
        <title>Best Meal Challenge</title>
        <description>Which community cooks the best meal?</description>
        <price>CHF 1000.- Gutschein</price>
        <registrations>
            <registration communityId="1">
                <date>15.02.2019</date>
                <title>Das besten Magebrot</title>
                <description>Wir stellen das beste Magebrot her und überzeugen damit schon seit Jahren unsere Gäste.</description>
            </registration>
        </registrations>
    </challenge>
    <challenge id="2" companyId="1">
        <title>The 2nd Challenge</title>
        <description>Which community cooks the best meal? - again</description>
        <price>CHF 2000.- Gutschein</price>
        <registrations>
            <registration communityId="1">
                <date>15.03.2019</date>
                <title>Das besten Magebrot</title>
                <description>Wir stellen das beste Magebrot her und überzeugen damit schon seit Jahren unsere Gäste.</description>
            </registration>
            <registration communityId="2">
                <date>17.03.2019</date>
                <title>Die grösste Pizza</title>
                <description>Wir stellen das beste Magebrot her und überzeugen damit schon seit Jahren unsere Gäste.</description>
            </registration>
        </registrations>
    </challenge>
</challenges>
