=== TheHuebschi/xml-webapp/database/companies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="companies">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="company" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:unique name="companyId">
      <xs:selector xpath="company"/>
      <xs:field xpath="@id"/>
    </xs:unique>
    
  </xs:element>

  <xs:element name="company">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="name"/>
        <xs:element type="xs:string" name="description"/>
        <xs:element type="xs:string" name="location"/>
        <xs:element type="xs:string" name="numberOfEmployees"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="id" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== TheHuebschi/xml-webapp/database/companies.xml
<?xml version="1.0" ?>
<companies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="companies.xsd">
    <company id="1">
        <name>IKEA</name>
        <description>asdfsd ökasdf ökuh</description>
        <location>Rothenburg</location>
        <numberOfEmployees>300</numberOfEmployees>
    </company>
    <company id="2">
        <name>Schnittlauch AG</name>
        <description>TestText</description>
        <location>Lauffeburg</location>
        <numberOfEmployees>283</numberOfEmployees>
    </company>
</companies>
